//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNTPExercise_SimpleTwitter.Models
{
    using System;
    using System.Collections.Generic;

    public partial class UserComment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
