//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MicroBlog
    {
        public int CommentID { get; set; }
        public string CommentUserName { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CommentPostDate { get; set; }
    }
}
