//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jrmmba_SimpleTwitter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tblTweet
    {
        public int tweetID { get; set; }

        [Required(ErrorMessage = "No Anonymous Tweets! Name cannot be blank and should be within 30 characters")]
        [StringLength(30)]
        [DisplayName("Tweeter's Name")]
        public string userName { get; set; }

        [Required(ErrorMessage = "Say something and keep it under 140 characters")]
        [StringLength(140)]
        [DisplayName("Tweet")]
        public string theTweet { get; set; }

        [DisplayName("Date Tweeted")]
        public System.DateTime dateCreate { get; set; }
    }
}
