//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTwitter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentTable
    {
        public int Comment_Id { get; set; }
        public string Comment_Name { get; set; }
        public string Comment_Comment { get; set; }
        public System.DateTime Comment_Date { get; set; }
    }
}
